version: '3'

services:
  p00:
    image: sko9370/rpi:p00
    ports:
      - "50000:80"
    deploy:
      replicas: 1
  p01:
    image: sko9370/rpi:p01
    ports:
      - "50100:8000"
    deploy:
      replicas: 1
  p03:
    image: sko9370/rpi:p03
    ports:
      - "50300:80"
    deploy:
      replicas: 1 
  p04:
    image: sko9370/rpi:p04
    ports:
      - "50400:80"
    deploy:
      replicas: 1 
  p05:
    image: sko9370/rpi:p05
    ports:
      - "50500:8000"
    deploy:
      replicas: 1 
  p06:
    image: sko9370/rpi:p06
    ports:
      - "50600:8000"
    deploy:
      replicas: 1 
  p08:
    image: sko9370/rpi:p08
    ports:
      - "50800:80"
    deploy:
      replicas: 1 
  p09:
    image: sko9370/rpi:p09
    ports:
      - "50900:8000"
    deploy:
      replicas: 1 
  p10:
    image: sko9370/rpi:p10
    ports:
      - "51000:80"
    deploy:
      replicas: 1 
  viz:
    image: sko9370/rpi:viz
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
