version: '3'

services:
  dvwa:
    image: dvwa:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
  viz:
    image: viz:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"