version: '3'

services:
  dvwa1:
    image: sko9370/rpi:dvwa 
    ports:
      - "91:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  dvwa2:
    image: sko9370/rpi:dvwa 
    ports:
      - "92:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  dvwa3:
    image: sko9370/rpi:dvwa 
    ports:
      - "93:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
