version: '3'

services:
  dvwa1:
    image: sko9370/rpi:dvwa 
    ports:
      - "71:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  dvwa2:
    image: sko9370/rpi:dvwa 
    ports:
      - "72:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  dvwa3:
    image: sko9370/rpi:dvwa 
    ports:
      - "73:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
