version: '3'

services:
  dvwa1:
    image: sko9370/rpi:dvwa 
    ports:
      - "81:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  dvwa2:
    image: sko9370/rpi:dvwa 
    ports:
      - "82:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  viz:
    image: sko9370/rpi:viz 
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
